# Dockerfile.ingest
FROM python:3.9

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
RUN pip install pandas sqlalchemy psycopg2-binary

WORKDIR /app

COPY ingest_data.py .

ENTRYPOINT ["python", "ingest_data.py"]