version: 2

sources:
  - name: staging
    database: zoomcamp-455010
    schema: trips_data_all
      # loaded_at_field: record_loaded_at
    tables:
      - name: int_green_rides
      - name: int_yellow_rides
         # freshness:
           # error_after: {count: 6, period: hour}

